### ISSUE TITLE
Livebridge "startdate" in control.yml

### ISSUE THREAD

**Issue by martinvirtel** [dpa-newslab/livebridge#2]
It would mean the date and time when the live stream is expected to begin to fire. 

I need it to to communicate future liveblog events to Tickaroo. The Livebridge would ignore the property.

![image](https://cloud.githubusercontent.com/assets/9485782/26199403/2006c9ee-3bca-11e7-9be9-ff651881b893.png)

For a future iteration, livebridges might want to sync their settings in some pub/sub way.

**Comment by mborho** [comment]
Should be part of the specific service plugin, not of livebridge itself.
