### ISSUE TITLE
Instagram posts don't get forwareded to ScribbleLive

### ISSUE THREAD

**Issue by martinvirtel** [dpa-newslab/livebridge#4]
... since Sourcefabric switched to embed.ly

**Comment by mborho** [comment]
Since all embed-related code is stripped out of in the LB API, perhaps using the Instagram-API for generating embed codes would be feasible: https://www.instagram.com/developer/embedding/

**Comment by mborho** [comment]
Fixed in https://github.com/dpa-newslab/livebridge-scribblelive/commit/1bcf50ad75aaec8d7e4d909fff851f9235fa900b

New plugin version after other issues resolved too.
