### ISSUE TITLE
Twitter posts show duplicate Text when forwarded to ScribbleLive

### ISSUE THREAD

**Issue by martinvirtel** [dpa-newslab/livebridge#5]
... since Sourcefabric switched to embed.ly

![image](https://user-images.githubusercontent.com/9485782/40837013-2ccb2144-6599-11e8-978d-2d3b670a9ee0.png)

**Comment by mborho** [comment]
Probably an editors task, since the description-text of the embed is pre-filled in the Liveblog editor with the tweet text. But since it is editable, it should probably not be stripped, but cleansed before publishing?

**Comment by martinvirtel** [comment]
Currently an Editor Task
